DROP TABLE IF EXISTS score;

CREATE TABLE score (
    obtained_at DATETIME NOT NULL PRIMARY KEY DEFAULT CURRENT_TIMESTAMP,
    level INTEGER NOT NULL,
    lines INTEGER NOT NULL,
    points INTEGER NOT NULL
);

CREATE INDEX score_points_idx ON score (points DESC);