DROP TABLE IF EXISTS score;

CREATE TABLE score (
    _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    obtained_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP UNIQUE,
    level INTEGER NOT NULL,
    lines INTEGER NOT NULL,
    points INTEGER NOT NULL
);

CREATE INDEX score_points_idx ON score (points DESC);